### ISSUE TITLE
Creación de Modelos

### ISSUE THREAD

**Issue by gonzalejandro** [DCC-CC4401/2018-2-Tiburoncin-hu-ha-ha-T2#1]
Necesitamos crear los siguientes modelos. Hasta el momento, se tienen los siguientes atributos:
- Persona:
  - Nombre
  - Apellido Materno
  - Apellido Paterno
  - Rut
  - Correo

- Estudiante
 - Hereda propiedades de Persona

- Cursos:
  - Código
  - Nombre
  - Número de Sección
  - Año
  - Semestre

- Coevaluación:
  - Estado (Abierto o cerrado)
  - Fecha de inicio/fin

**Comment by frmunozz** [comment]
Se modifican algunos puntos:

* Se crea una entidad User que generaliza a las personas naturales y a los administradores

* se dejan dos sub entidades que heredan de User las cuales definen persona natural y admin. Estas por ahora no tienen diferencia mayor pero siento que da mayor claridad.

* Apellido paterno y materno se juntan en un solo atributo llamado apellido.

* Entidad Estudiante ya no es necesaria.

* Coevaluaciones no tendrán atributo estado, este se define como propiedad el cual entregará True cuando el tiempo del servidor esté entre el tiempo inicio y tiempo fin.

Modificaciones agregadas al repositorio.
