### ISSUE TITLE
Terminar Mockups en Balsamiq

### ISSUE THREAD

**Issue by gonzalejandro** [DCC-CC4401/2018-2-Tiburoncin-hu-ha-ha-T2#4]
Terminar la ficha que falta. Una vez terminada, agregar dentro del directorio /T2 una carpeta /mockups que contenga imágenes de cómo debiera quedar cada view en la resolución solicitada por el cliente (o mayor).

**Comment by frmunozz** [comment]
Mockups terminados y subidos, las vistas de cada interfaz están separadas por tipo de usuario, para visualizar mejor las diferencias.
